// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqNmcC9TSi3oEcQzcjLwD6ZIKCMYKb8og',
    appId: '1:219448270175:web:9f9d021f770d332cddaaea',
    messagingSenderId: '219448270175',
    projectId: 'your-recipes-9230f',
    authDomain: 'your-recipes-9230f.firebaseapp.com',
    storageBucket: 'your-recipes-9230f.firebasestorage.app',
    measurementId: 'G-3D3FE59NTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuUo2g31Twnm6k9pzStLIXHXG3j98fGik',
    appId: '1:219448270175:android:23ab290116e249caddaaea',
    messagingSenderId: '219448270175',
    projectId: 'your-recipes-9230f',
    storageBucket: 'your-recipes-9230f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbDcbHQ6VvT29pWLSXfFBiRAcu57MVKZc',
    appId: '1:219448270175:ios:8dd8cc894a2c9c18ddaaea',
    messagingSenderId: '219448270175',
    projectId: 'your-recipes-9230f',
    storageBucket: 'your-recipes-9230f.firebasestorage.app',
    iosBundleId: 'com.BrewWisdom.WV67Application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbDcbHQ6VvT29pWLSXfFBiRAcu57MVKZc',
    appId: '1:219448270175:ios:807901afa95542c8ddaaea',
    messagingSenderId: '219448270175',
    projectId: 'your-recipes-9230f',
    storageBucket: 'your-recipes-9230f.firebasestorage.app',
    iosBundleId: 'com.example.bear',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqNmcC9TSi3oEcQzcjLwD6ZIKCMYKb8og',
    appId: '1:219448270175:web:930930286c2a85b7ddaaea',
    messagingSenderId: '219448270175',
    projectId: 'your-recipes-9230f',
    authDomain: 'your-recipes-9230f.firebaseapp.com',
    storageBucket: 'your-recipes-9230f.firebasestorage.app',
    measurementId: 'G-G72L9VDXCH',
  );
}
